---
deployment:
  tasks:
    # Set the deployment path
    - export DEPLOYPATH=/home/dreamlhf/dynamic.dreamlineet.com
    # Set the repository path
    - export REPOPATH=/home/dreamlhf/repositories/Dreamline_ai
    # Remove previous old files, if any
    - /bin/rm -Rf ${DEPLOYPATH}_old
    # Copy old site files to another directory
    - /bin/cp -R ${DEPLOYPATH} ${DEPLOYPATH}_old
    # Sync repository files to the deploy target path, excluding .git folder
    - /bin/rsync -aP --exclude '.git' --exclude '.well-known' --exclude 'node_modules' ${REPOPATH}/ ${DEPLOYPATH} --delete-after
    # Set correct permissions
    - /bin/chmod 755 ${DEPLOYPATH}
    - /bin/find ${DEPLOYPATH} -type d -exec /bin/chmod 755 '{}' \;
    - /bin/find ${DEPLOYPATH} -type f -exec /bin/chmod 644 '{}' \;
    # Install dependencies and build Next.js app
    - cd ${DEPLOYPATH} && npm ci --production
    - cd ${DEPLOYPATH} && NODE_ENV=production npm run build
