---
deployment:
  tasks:
    - /bin/cp -R * /home/dreamlhf/dynamic.dreamlineet.com/
    - cd /home/dreamlhf/dynamic.dreamlineet.com && npm ci --production
    - cd /home/dreamlhf/dynamic.dreamlineet.com && npm run build
