---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$dreamlhf/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH 2>/dev/null || :
    - cd $DEPLOYPATH
    - npm ci --production
    - NODE_ENV=production npm run build
    - /bin/cp -R out/* $DEPLOYPATH
    - /bin/rm -rf node_modules out package*.json src .next .git* *.md *.yml *.json *.ts *.js deploy.sh 2>/dev/null || :