---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dreamlhf/dynamic.dreamlineet.com
    - /bin/cp -R /home/dreamlhf/repositories/Dreamline_ai/* $DEPLOYPATH/
    - cd $DEPLOYPATH
    - npm ci --production
    - NODE_ENV=production npm run build
